# Generated by Django 4.1.1 on 2022-09-12 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account_book", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accountbook",
            old_name="book_name",
            new_name="book_title",
        ),
        migrations.RenameField(
            model_name="accountbookrecord",
            old_name="price",
            new_name="amount",
        ),
        migrations.RemoveField(
            model_name="accountbookrecord",
            name="account_book_category",
        ),
        migrations.DeleteModel(
            name="AccountBookCategory",
        ),
    ]
